--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2025-04-01 13:40:28

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4874 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 17517)
-- Name: chat_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_message (
    chat_room_id bigint,
    id bigint NOT NULL,
    "timestamp" timestamp(6) without time zone,
    user_id bigint,
    content character varying(255),
    file_url character varying(255)
);


ALTER TABLE public.chat_message OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17516)
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17525)
-- Name: chat_room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_room (
    is_group boolean NOT NULL,
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.chat_room OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17524)
-- Name: chat_room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 17511)
-- Name: chat_room_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_room_members (
    chat_room_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.chat_room_members OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 17510)
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_id_seq OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17530)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 4865 (class 0 OID 17517)
-- Dependencies: 218
-- Data for Name: chat_message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_message (chat_room_id, id, "timestamp", user_id, content, file_url) FROM stdin;
1	1	2025-03-19 19:20:21.556893	1	Hello, WebSocket!	\N
1	2	2025-03-29 11:43:59.391122	1	Вот фото!	http://localhost:9000/chat-bucket/f6b6e445-c107-4e05-bc85-74269200c647-test-photo.jpg
1	35	2025-03-29 12:49:39.685638	1	Вот фото!	http://localhost:9000/chat-bucket/985afb2d-6ace-405b-81cc-eb1e4d706cee-test-photo.jpg
1	36	2025-03-29 12:50:07.877835	1	Вот фото!	http://localhost:9000/chat-bucket/cfa03ea3-47b3-442b-86aa-12da24dd1091-test-photo.jpg
\.


--
-- TOC entry 4867 (class 0 OID 17525)
-- Dependencies: 220
-- Data for Name: chat_room; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_room (is_group, id, name) FROM stdin;
f	1	Private Chat
\.


--
-- TOC entry 4863 (class 0 OID 17511)
-- Dependencies: 216
-- Data for Name: chat_room_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_room_members (chat_room_id, user_id) FROM stdin;
1	2
1	1
\.


--
-- TOC entry 4868 (class 0 OID 17530)
-- Dependencies: 221
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, email, password, role, username) FROM stdin;
1	d.pavlov04@gmail.com	$2a$10$ZyfDoT0zXKVxDNwKA9Bc.ux.UfndEmP/dQSzZth.GJ14dNO8g8Fcq	ROLE_USER	Tyzer
2	test_example	$2a$10$SQwet2KYkPuxPsjXa5Nebev62i4rWQ3aQ7JEWqzFPzvvw3dZMp8de	ROLE_USER	Ramzy
3	example@mail.ru	$2a$10$CLwxv6BQfTuXeZ462i9uLeb4OUzd5x7BkjFpRkSV3POnY5773EW2u	ROLE_USER	TestUser2
4	testemail@mail.ru	$2a$10$GhvoacDAeQuRD4ZR8M6ztu5g0SB3OfAV42kmzfKk9XjmcbKh9EYvW	ROLE_USER	test_user
\.


--
-- TOC entry 4875 (class 0 OID 0)
-- Dependencies: 217
-- Name: chat_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_message_id_seq', 36, true);


--
-- TOC entry 4876 (class 0 OID 0)
-- Dependencies: 219
-- Name: chat_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_room_id_seq', 1, true);


--
-- TOC entry 4877 (class 0 OID 0)
-- Dependencies: 215
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_id_seq', 4, true);


--
-- TOC entry 4706 (class 2606 OID 17523)
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- TOC entry 4704 (class 2606 OID 17515)
-- Name: chat_room_members chat_room_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room_members
    ADD CONSTRAINT chat_room_members_pkey PRIMARY KEY (chat_room_id, user_id);


--
-- TOC entry 4708 (class 2606 OID 17529)
-- Name: chat_room chat_room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room
    ADD CONSTRAINT chat_room_pkey PRIMARY KEY (id);


--
-- TOC entry 4710 (class 2606 OID 17539)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4712 (class 2606 OID 17537)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4714 (class 2606 OID 17541)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 4715 (class 2606 OID 17547)
-- Name: chat_room_members fk4yp21jl4obii8479tewtkd122; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room_members
    ADD CONSTRAINT fk4yp21jl4obii8479tewtkd122 FOREIGN KEY (chat_room_id) REFERENCES public.chat_room(id);


--
-- TOC entry 4716 (class 2606 OID 17542)
-- Name: chat_room_members fkbemsjj4g0iny4xpkvj5rwj6ab; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room_members
    ADD CONSTRAINT fkbemsjj4g0iny4xpkvj5rwj6ab FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4717 (class 2606 OID 17557)
-- Name: chat_message fkd3oo2bhroe16913kh5pwtgk3h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT fkd3oo2bhroe16913kh5pwtgk3h FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4718 (class 2606 OID 17552)
-- Name: chat_message fkj52yap2xrm9u0721dct0tjor9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT fkj52yap2xrm9u0721dct0tjor9 FOREIGN KEY (chat_room_id) REFERENCES public.chat_room(id);


-- Completed on 2025-04-01 13:40:28

--
-- PostgreSQL database dump complete
--

